# Generated by Django 3.1.7 on 2021-03-15 08:59

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='document_type',
            field=django_mysql.models.EnumField(choices=[('ar', 'Article'), ('co', 'Conference'), ('bc', 'Book Chapter'), ('bo', 'Book'), ('mt', 'Master Thesis'), ('pt', 'PhD Thesis'), ('ot', 'Other')], default='ot'),
        ),
    ]
