# Generated by Django 3.1.7 on 2021-03-15 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0002_paper_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='doi',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='paper',
            name='source_title',
            field=models.CharField(max_length=255),
        ),
    ]
