# Generated by Django 3.1 on 2021-04-22 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0009_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='path',
            field=models.FilePathField(),
        ),
    ]
