# Generated by Django 3.1 on 2021-04-22 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0010_auto_20210422_0420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='path',
            field=models.CharField(max_length=255),
        ),
    ]
